# Generated by Django 3.1.5 on 2021-02-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_post_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='posts'),
            preserve_default=False,
        ),
    ]
